### PR TITLE
Button UI Revamp

### PR DESCRIPTION
**Pull request by sidsharma2002**
https://user-images.githubusercontent.com/53833109/194798389-2fc917a7-c755-49ee-a871-0d14d427da1f.mp4

### CODE REVIEW

**Comment by sidsharma2002** [comment]
@sebastiangaertner @Elforama how does this looks like?

**Comment by sebastiangaertner** [comment]
@sidsharma2002 it will def be a great improvement for the users. I like it. Jonathan is this something that can be included in the next version already?

**Comment by EngrTaofeek** [comment]
@sidsharma2002 Great this animation looks better. Also leave the corner radius as it is or increase it so the buttons don't have very sharp edges.

**Comment by EngrTaofeek** [comment]
This the Figma file although it's been inactive for a while https://www.figma.com/file/hn67qtbMN1aP3yrXx69dP2/Android-UX-(v2---w%2F-messaging-1.0.5)?node-id=0%3A386

**Comment by EngrTaofeek** [comment]
@sebastiangaertner I was thinking since we have more UI/UX volunteers it might be better to let them review generally also since the project itself needs a design review. If we could try to set up a call this week that would be great. Jacob was unavailable last week so we couldn't get much done.

**Comment by sidsharma2002** [comment]
> @sidsharma2002 this animation looks great. Also leave the corner radius as it is or increase it so the buttons don't have very sharp edges.

got it! 15dp is looks good to me

**Comment by Elforama** [comment]
I think as long as we add back the regular button depth and soft edges, this is better than what we had. @sebastiangaertner  any concerns here? Otherwise I'd like to get this change in.

**Comment by sidsharma2002** [comment]
@Elforama when are we thinking to get this merged?

**Comment by Elforama** [comment]
Sorry for the delay here.

I tested this out and noticed a couple things.
1. We should leave the edge radius at 30
2. This only affects square buttons, giving an inconsistent feel. Can we also apply this update to circular buttons?

With those fixes I can merge this.

**Comment by Elforama** [comment]
This was handled in another PR: https://github.com/Greenstand/treetracker-android/pull/1037

**Pull request closed without merging**
