### PR TITLE
Made Custom snackbar and implemented validation error messages in them.

### LINKED ISSUE #859: Snack bar for phone or email validation error

### PR DESCRIPTION
**Pull request by EngrTaofeek**
Fixes #859 Made Custom snackbar and implemented validation error messages in them.
I think the previous refactor of composable into EmailTextField is a bit unnecessary as it uses a lot of values in CredentialEntry composable now the function takes in 6 parameters that are constants.

### CODE REVIEW

**Comment by ZavenArra** [comment]
When I click that done button, the keyboard does not hide, so I do not see the custom message.   Can we put the message above the keyboard, or hide the keyboard when the done typing button is tapped.

**Review by ZavenArra — CHANGES_REQUESTED** [review]
When I click that done button, the keyboard does not hide, so I do not see the custom message. Can we put the message above the keyboard, or hide the keyboard when the done typing button is tapped.

**Comment by Elforama** [comment]
What if we show the error on the text input where the input goes red?

**Comment by EngrTaofeek** [comment]
> What if we show the error on the text input where the input goes red?

We would also have to show the error message outside the inbox field so the user knows what to do.

**Review by ZavenArra — APPROVED** [review]

**Pull request merged**
