### PR TITLE
no language default

### PR DESCRIPTION
**Pull request by ZavenArra**
- wip: attempt no language default
- feat: implement no default language

### CODE REVIEW

**Review by Elforama — CHANGES_REQUESTED** [review]
Please see comment above

**Comment by ZavenArra** [comment]
I believe @snacks's determination was that there would be no initial language default.  That's also what Karen was confused about - the initial language selection screen.

**Comment by Elforama** [comment]
@ZavenArra Im confused -> https://github.com/Greenstand/treetracker-android/issues/828

**Comment by ZavenArra** [comment]
I am also confused.

Also one of the main use cases we have heard about in the past is that users will have devices that are set to english, but actually want to see Swahili in the app but don't know how to change this universally in the settings right when they are using the device. 

The other issue is that some of our testers are not clear on what to do on the language selection screen.

**Comment by snacks** [comment]
Yes I see the confusion here, which is mostly on me. Sorry about that! The initial assumption was that users would know a language button was already selected when they come to that screen but testing is showing that to not be true. Reading the above case that phones could be initially set to English but the user would prefer Swahili reinforces this decision to not have a "default" language.


I think a better way to describe this ticket would be that we want there to be "no selected language" on the language selection screen the first time the user visits. When they re-visit the language selection screen the language they previously selected should be selected.

**Comment by ZavenArra** [comment]
@Elforama I think this PR provides the functionality the @snacks described.

**Pull request merged**
