### PR TITLE
Add temp org screen

### PR DESCRIPTION
**Pull request by Elforama**
This adds a temporary screen between selecting a wallet and planting trees to allow adding an org for the session.

### CODE REVIEW

**Comment by ZavenArra** [comment]
Verified working, and verified the org field is populated in the bulk pack.  However need once change, the organization needs to be 'sticky' - we can expect our users to type it in each time or remember it.

**Review by ZavenArra — CHANGES_REQUESTED** [review]
The feature is working well.  We need one addition - the organization needs to be sticky and pre-populate the input field with the most recent value that was entered.

In general our users often will not remember the specific organization name they are given, so it's important that this is saved the first time time it is entered.  We may need to label the field in this case well, since if it is prepopulated it might not be clear what the field is for.

**Comment by EngrTaofeek** [comment]
@ZavenArra Another option which is more of a permanent solution to have a list of organisations displayed like those language buttons and make them selectable. It solves both it been sticky and prevents wrong spellings.

**Review by EngrTaofeek — APPROVED** [review]
Other than Zaven's request, this is good.

**Comment by Elforama** [comment]
@ZavenArra What if I add the button used in the language screen (style wise) to act as a "sticky" autofill. Pressing it autofills the selection, or can move onto the next screen. This would leave the form untouched with the default hint. When there was no previous org, the button would not show.

@EngrTaofeek Our long term solution is to not allow users to add orgs manually, so inputting will not work. We'll be using links to auto add orgs to an org screen that's accessible from the dashboard.

**Pull request merged**
