### PR TITLE
Credential /Name screen flash after selfie

### PR DESCRIPTION
**Pull request by EngrTaofeek**
(Not ready to be merged)I am trying to make a progressbar show instead of the flashes of the screen as highlited in issue #739 . But I am facing an issue accesing the SignupViewModel.kt, it shows no compile error but as soon as ImageReviewScreen.kt is to come on it shows white and doesn't review.  See attached screenshot on error showed. 
Screenshot 2022-01-16 at 14 41 00
Any tip on this?

### CODE REVIEW

**Comment by Elforama** [comment]
I'm not sure this is the correct approach. Now instead of the signups screen flashing, a loading screen will flash. Maybe we can move the logic that saves the user to the last screen so there is no need to go back.

**Comment by EngrTaofeek** [comment]
> I'm not sure this is the correct approach. Now instead of the signups screen flashing, a loading screen will flash. Maybe we can move the logic that saves the user to the last screen so there is no need to go back.

that sounds better

**Comment by ZavenArra** [comment]
Was a solution to this issue found and implemented?

**Comment by Elforama** [comment]
Making progress. It's a small bug, but large complex fix

**Pull request closed without merging**
