### PR TITLE
Solution  for Issue 68

### PR DESCRIPTION
**Pull request by beastlyCoder**

### CODE REVIEW

**Comment by deepwinter** [comment]
hi @beastlyCoder .. I'm confused about this PR, it seems to contain just all the commits from master merged into an older branch.  Can you inform me on where the fix is and what's getting fixed??  Thanks for joining!!!

**Comment by beastlyCoder** [comment]
Yeah sorry I had an issue committing yesterday, I am new to using Android Studio and making pull requests from within Android Studio.

**Comment by deepwinter** [comment]
No worries.  Please make all PR against up to date master branch!

**Comment by beastlyCoder** [comment]
Alright thank you. I'm confused as to why when I make changes in my android studio that it says there are no local updates.

**Comment by deepwinter** [comment]
I'm gonna reject this PR, and wait for you to submit a clean PR.  Thanks for updating!!

**Pull request closed without merging**
