### PR TITLE
Issue 112

### PR DESCRIPTION
**Pull request by dezidaisy**
Fix for Issue 112

### CODE REVIEW

**Comment by ryan-beckett** [comment]
I would have expected to see the use of `BitmapFactory.Options.inBitmap` to implement the re-use of allocated memory.

**Comment by dezidaisy** [comment]
I'm not sure but I think that using BitmapFactory.Options.inBitmap would prevent reserving memory used to declare it early on but it has its own limitations like size issues, etc..

**Comment by ryan-beckett** [comment]
I don't follow. The docs state that `inBitMap` when not null will used to hold the bitmap, so new heap space isn't allocated. I believe the "same-size" limitation was prior to API 19. I'm not trying to be combative, I just don't see why that field isn't set, especially when the tutorial you referenced did exactly that.

**Comment by dezidaisy** [comment]
Yes but we may not need those specifications. They might be restrictive. I think this simple approach will improve things. Anyway, no harm done!

**Comment by deepwinter** [comment]
Has this fix been tested in our app?  Before I merge this I would need to see some before/after memory allocation profiling, like in the article referenced in #112

**Comment by dezidaisy** [comment]
I will test it out soon.

**Comment by dezidaisy** [comment]
Sorry not able to test it out. I keep getting insufficient accuracy.

**Comment by deepwinter** [comment]
You should build against the build variant 'dev' instead of 'debug'.  The dev build variant allows for creating trees without a specific accuracy.

**Comment by dezidaisy** [comment]
Ok I will try that.. :)

**Pull request closed without merging**
