### PR TITLE
Offset -90 degree image rotation that happens on resizing

### PR DESCRIPTION
**Pull request by arunbakt**
Offsets the -90 degree image rotation that happens on resize

### CODE REVIEW

**Comment by deepwinter** [comment]
Does the rotation happen on ALL phones, or just particular phones?

**Comment by arunbakt** [comment]
It happens on my s8 galaxy. Not sure about other phones.

**Comment by deepwinter** [comment]
There is a common bug in Android since the very beginning of Android where SOME phones mis-identify the orientation of an image, and produce rotated images.  This does not occur on ALL phones.  So we need to make sure we understand how to know the correct orientation of the image (perhaps manually checking the aspect ratio) to make sure we are not introducing rotation in some cases where we think we are fixing it, but are actually correct.   Are you familiar with this classic issue?

**Comment by deepwinter** [comment]
I tested on 3 android phones and they all show the rotation bug (Pixel2, Galaxy A20s, Y9)

**Comment by deepwinter** [comment]
Also tested on an old, terrible Android, J3v6.  Also rotates.  So that's good news, this might not be different across devices.

**Pull request merged**
