### PR TITLE
replaced placeholder images and updated dashboard screen

### PR DESCRIPTION
**Pull request by EngrTaofeek**
Replaced placeholder images and updated dashboard screen.

### CODE REVIEW

**Review by Elforama — APPROVED** [review]
This looks great, thanks! Please make sure that it passes the tests, and I'll have it merged.

**Review by Elforama — CHANGES_REQUESTED** [review]
The reason it doesn't compile is due to the icons being in the greenstand flavor. You need to add them to the 'main' res folder.

**Comment by EngrTaofeek** [comment]
> The reason it doesn't compile is due to the icons being in the greenstand flavor. You need to add them to the 'main' res folder.

This was probably the same reason why my previous PR failed, I would fix them both now. Thanks for pointing out. I was already reading the failed log and trying to make some sense from it.

**Review by Elforama — CHANGES_REQUESTED** [review]
Please remove the images from the greenstand files.

The way this works is that the app will use whatever is in the main folder. But if something is provided in the greenstand folder it will use it instead. Since we only want one copy of the icons for all builds, we should only have them in the main folder.

**Comment by EngrTaofeek** [comment]
> Please remove the images from the greenstand files.
> 
> The way this works is that the app will use whatever is in the main folder. But if something is provided in the greenstand folder it will use it instead. Since we only want one copy of the icons for all builds, we should only have them in the main folder.

Done

**Review by Elforama — CHANGES_REQUESTED** [review]
Please double check your PRs. The images are still in the Greenstand flavor.

**Comment by EngrTaofeek** [comment]
> Please double check your PRs. The images are still in the Greenstand flavor.

The images were deleted in a previous commit but merging remote added them now. I have fixed it in a new commit https://github.com/Greenstand/treetracker-android/pull/692/commits/c36663cdb3afc10e9ca6202728625e4ec9e7fa93.

**Pull request merged**
